### ISSUE TITLE
Add native, docker-less support for Linux

### ISSUE THREAD

**Issue by ESultanik** [crytic/solc-select#19]
This should also resolve #12.

## Task Description
There is no reason why `solc-select` would need to use Docker on Linux, since `solc` distributes statically linked Linux binaries.

The goal is to update the `solc-select` install script to:
- [x] Detect whether it is being installed on Linux
- [x] If so, run the scripts that are typically used to provision the Docker image

This may require modifying the install scripts such that they can _both_ provision the Docker image (for non-Linux users) _and_ install the scripts natively in Linux. The scripts that are installed in the Docker image are in the [`scripts/`](https://github.com/crytic/solc-select/tree/master/scripts) directory.

There is currently [a development branch](https://github.com/crytic/solc-select/tree/dev-fix-ubuntu) that provides interim support for Ubuntu, but it uses Docker, which should not be necessary.

## Acceptance criteria
- [x] `solc-select` can install and upgrade itself on Ubuntu 18.04.2 LTS
- [x] `solc-select` can install and upgrade itself on macOS
- [x] `solc-select` behaves identically regardless of the OS on which it is run
- [x] Documentation is updated to reflect the new capabilities, as well as any changes to the installation instructions

It would be nice to have `solc-select` packaged in a more standard way (_e.g._, Homebrew for macOS and Apt for Linux), but this is not necessary.

## Required Skill
- [x] Experience with Bash scripting
- [x] Experience with Docker
- [x] Experience with Linux

No experience with `solc` or smart contracts is required.

Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/solc-select/19/3221).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/solc-select/19/3221).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $131,426.22 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [aerophile](https://gitcoin.co/profile/aerophile) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/solc-select/19/3221?mutate_worker_action=approve&worker=aerophile) | [reject worker](https://gitcoin.co/issue/crytic/solc-select/19/3221?mutate_worker_action=reject&worker=aerophile))_.**

Hey,
i have skills in both linux, bash and docker. The method I'll use is as follows:
(1) Study the existing Dockerfile 
(2) Implement the Installation steps from Dockerfile as bash script
(3) Test it out on Linux machines and MacOS to complete the task

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/solc-select/19/3221).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [aerophile](https://gitcoin.co/profile/aerophile) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/solc-select/19/3221?mutate_worker_action=approve&worker=aerophile) | [reject worker](https://gitcoin.co/issue/crytic/solc-select/19/3221?mutate_worker_action=reject&worker=aerophile))_.**

Hey,
i have skills in both linux, bash and docker. The method I'll use is as follows:
(1) Study the existing Dockerfile 
(2) Implement the Installation steps from Dockerfile as bash script
(3) Test it out on Linux machines and MacOS to complete the task

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/solc-select/19/3221).

**Comment by ivanvpan** [comment]
Thanks for assigning to me, I appreciate your trust. I will have it delivered on or before Tuesday Jul 30.

**Comment by gitcoinbot** [comment]
@ivanvpan Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=100)

**Comment by ceresstation** [comment]
Hi @ivanvpan it's now July 30th, if we don't hear back in 24 hours we'll have to pass the task to @balajipachai

**Comment by ivanvpan** [comment]
My changes can be seen here and generally I'm satisfied, except some variable naming and README work:
https://github.com/crytic/solc-select/compare/master...ivanvpan:gitcoin-linux-no-docker?expand=1

I got tripped by the problem that I am not at all able to run solc-select dockerized script on Linux, even the original upstream version. I wanted to make sure that there are no regressions, but on both Arch and Ubuntu it fails with `chroot: can't execute 'chroot.sh': No such file or directory`. Actually no command is able to run in that chroot. The `/workdir` mounts all look fine. One possible reason is that the libc in `/lib` and `/usr/bin/*` have a mismatch and no binaries are able to run. How it runs for anybody though is puzzling to me, I'll try OS X today and see how that works.

Noticed that `find` does not necessarily pick the correct solc-default, because 0.5.9 ranks lexically higher than 0.5.10.

Also, in a few cases installation via `bash -e` fails, for example when there's no `solc" installed and `which solc` returns a non-zero code.

I spent a lot of time trying to fix the above, thus the general delay.

**Comment by ivanvpan** [comment]
Ok, I'm done with code.
Wrote a test for Linux that creates a docker image runs solc-select inside.
Updated README.
Removed all debugging flags.

But if could have a little more patience, I am trying to procure an OSX machine to run the final test. You should have my sign-off very soon.

Here's the comparison again:
https://github.com/crytic/solc-select/compare/master...ivanvpan:gitcoin-linux-no-docker?expand=1

**Comment by SlightlyCyborg** [comment]
I'm having trouble installing on linux, so I hope this gets merged soon :)

**Comment by gitcoinbot** [comment]
@ivanvpan Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/solc-select/19/3221?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 200.0 DAI (200.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@ivanvpan](https://gitcoin.co/profile/ivanvpan)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/crytic/solc-select/pull/23) by @ivanvpan

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/solc-select/19/3221)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/solc-select/19/3221).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $150,014.57 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by ivanvpan** [comment]
@ceresstation Hey. This was closed, can you mark my bounty as complete please? I don't care as much for the cash as having a record of having completed a bounty =)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @ivanvpan.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/solc-select/19/3221)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $135,394.90 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
